version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo Setting IMAGE_TAG to build ID...
      - export IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | sed 's/:/_/g')
      - echo "AWS_REGION=$AWS_REGION" >> env_vars
      - echo "ECR_REPOSITORY_URI=$ECR_REPOSITORY_URI" >> env_vars
      - echo "ECR_REPOSITORY_API=$ECR_REPOSITORY_API" >> env_vars
  build:
    commands:
      - echo Building Docker image...
      - echo $IMAGE_TAG
      - docker build -t $ECR_REPOSITORY_API:$IMAGE_TAG .
      - echo Tagging the image with 'latest'...
      - docker tag $ECR_REPOSITORY_API:$IMAGE_TAG $ECR_REPOSITORY_URI/$ECR_REPOSITORY_API:latest
      - docker tag $ECR_REPOSITORY_API:$IMAGE_TAG $ECR_REPOSITORY_URI/$ECR_REPOSITORY_API:$IMAGE_TAG
      - $ECR_REPOSITORY_URI/$ECR_REPOSITORY_API:latest > imagedefinitions.json
      - cat imagedefinitions.json
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR with build ID tag...
      - docker push $ECR_REPOSITORY_URI/$ECR_REPOSITORY_API:$IMAGE_TAG
      - echo Pushing Docker image to Amazon ECR with 'latest' tag...
      - docker push $ECR_REPOSITORY_URI/$ECR_REPOSITORY_API:latest

artifacts:
  files: 
    - '**/*'
    - env_vars
    - imagedefinitions.json
